name: Update Coverage
on: push

jobs:
  container-job:
    runs-on: ubuntu-latest

    # runs all of the steps inside the specified container rather than on the VM host.
    # Because of this the network configuration changes from host based network to a container network.
    container:
      image:  node:10.16-jessie
    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
        ports:
        - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v1
    - name: update container
      run: apt-get update
    - name: install postgres with psql
      run: apt install -y --no-install-recommends postgresql-12-plsh postgresql-server-dev-12
    - name: test psql
      run: psql -U postgres -d postgres -h ${{ job.services.postgres.ports[5432] }} -c 'select 1;'
